
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./services/postgres
    image: sephy-postgres:15-alpine
    networks:
      - infra-network
    env_file:
      - ./services/postgres/secrets/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "/healthy.sh"]
      start_period: 30s
      interval: 1m30s
      timeout: 30s
      retries: 5
  
  n8n:
    container_name: n8n
    restart: unless-stopped
    image: n8nio/n8n:2.0.2
    ports:
      - "5678:5678"
    networks:
      - infra-network
    env_file:
      - ./services/n8n/secrets/.env
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    

volumes:
  n8n-data:
    driver: local
    name: n8n-data
  postgres-data:
    driver: local
    name: postgres-data

networks:
  infra-network:
    driver: bridge
    name: infra-network
